<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<?php if (count($block->getStores())>1): ?>
<?php $flags = $block->getFlags();?>
<?php $id = '-footer'?>
<?php 
    $flag = isset($flags[$block->getCurrentStoreId()]) ? $flags[$block->getCurrentStoreId()] :  $block->getViewFileUrl(('images/flags/'. $block->getStoreCode() .'.jpg'));
?>
<div class="top-form-language">
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span class="flag">
					<img loading="lazy" src="<?php echo $flag ?>" width="20" height="20" alt="<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>" />
				</span>
				<?php echo $block->escapeHtml($block->getStoreName()) ?>
				<?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/icon/down.phtml")->toHtml(); ?>
            </strong> 
        </div>
        <ul class="dropdown switcher-dropdown shadow"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null}}'>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <?php
                        $flag = isset($flags[$_lang->getStoreId()]) ? $flags[$_lang->getId()] :  $block->getViewFileUrl(('images/flags/'. $_lang->getCode() .'.jpg'));
                    ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
							<span class="flag"><img loading="lazy" src="<?php echo $flag ?>" width="20" height="20" alt="<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>" /></span>	
                            <?php echo $block->escapeHtml($_lang->getName()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
</div>
<?php endif; ?>
